### ISSUE TITLE
Some regression tests are numerically instable, seems to expose problem in GPU kernels

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#421] opened 2019-02-04 23:10 UTC
These tests seem to suffer from numeric instabilities when run on the GPU while being stable on the CPU. I am increasing the tolerance for now, but this requires more investigation. In particular it seems that resuming is still not fully working, too. 

tests/training/models/nematus/test_encdec_depth.sh
tests/training/restoring/multi-gpu/test_sync.sh

**Comment by emjotde** [comment] 2019-02-05 00:17
Also these:
tests/training/cost-functions/test_ce-sum.sh
tests/training/cost-functions/test_perplexity.sh

**Comment by emjotde** [comment] 2019-02-05 17:58
This one makes problems too: 
tests/training/models/nematus/test_wmt17_model.sh

Likely related to:
tests/training/models/nematus/test_encdec_depth.sh
as they both use deep RNN models with attention.

**Comment by snukky** [comment] 2020-01-22 13:56
As we have discussed earlier, there seemed to be a weird problem with eps in the Adam optimizer causing some instability, only on GPU. I can no longer reproduce this with v1.8.40, so it has to be fixed with recent changes. Also, the mentioned tests have changed since last year and should be more stable now.

**Closed by snukky** 2020-01-22 13:56 UTC
