### ISSUE TITLE
Gradient dropping should have one history per client, not the last 1.5 * |clients|

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-dev#91] opened 2017-07-18 08:21 UTC
Servers keep a view of each client for delta encoding pulls  Currently gradient dropping's server keeps the last 1.5 * |clients| histories.  Should be keeping one for each client.  Reduces memory consumption and code complexity.  

@afaji is on internship, but I wanted to keep a record of this issue.

**Comment by dr-alan-turing** [comment] 2017-07-25 19:51
It would be a bit more complicated than changing history_size_ to 1 * |clients|, though. I suggest the following approach:

We have a 2-dimensional vector like **clientParams[shard][client]** which holds for each _shard_ the last communicated params for each _client_ (GPU), and a single vector **latestParams[shard]** to hold the latest parameters of each shard. Then to compute the deltas for client _C_ from shard _S_, we simply calculate **deltas = latestParams[S] - clientParams[S][C]**. This is ultimately simpler and has the added benefit that we don't lose any deltas if one client is very slow (as is the case in the current implementation). Memory is still constant because of the sharding.

@kpu Does the above approach seem correct? It's how I'm implementing it in my MultiNode implementation (except that I have **clientParams[shard][node][client]** where _client_ corresponds to the GPU on _node_).

**Comment by afaji** [comment] 2017-07-25 20:18
Yes, that is the correct implementation.

**Comment by dr-alan-turing** [comment] 2017-07-29 19:58
Thanks for the confirmation @afaji. I've implemented it in my multi-node implementation and will soon do the same for the single-node AsyncGraphGroup. I'm also getting some very impressive words/sec now that communication across nodes is super cheap!

**Comment by afaji** [comment] 2017-08-01 06:01
@dr-alan-turing awesome! Have you done implementing on the single-node asyncGraphGroup yet? if so, you can open a PR. Otherwise, I am planning to do that this week so you don't have to.

**Comment by dr-alan-turing** [comment] 2017-08-01 21:30
@afaji I haven't touched the single-node AsyncGraphGroup yet because there are still occasional pushes to it and I want to make merging as easy as possible. My MultiNodeAsyncGraphGroup is very similar (and just as messy - again, to make merging easier) but has the updated gradient dropping implemented as described above. I am running my experiments next week and will fix any bugs I come across. My dissertation deadline is on the 18th of August and I'll make a pull request to push my MultiNode to master soon after.

**Comment by dr-alan-turing** [comment] 2017-08-02 18:26
@afaji I noticed the branches "grad_drop" and "graddropping_upd". Have those been merged into master? If not, are they stable and do they provide improvements to the implementation in master?

**Comment by afaji** [comment] 2017-08-03 13:05
@dr-alan-turing all have been merged.

**Comment by dr-alan-turing** [comment] 2017-08-03 13:27
@afaji Great. What about the quantization branch in your personal repo (fork)? [https://github.com/afaji/Marian/commits/quantize](here)

**Comment by afaji** [comment] 2017-08-03 15:36
@dr-alan-turing nah, that's just an experimental. I'm just playing around with stuff.

**Comment by dr-alan-turing** [comment] 2017-08-03 20:26
@afaji How stable would you say the quantization is? It could be very useful for my experiments!

**Comment by afaji** [comment] 2017-08-04 08:53
Hmmm, it is not an actual quantization, It's just a simulated quantization. Also, it will make things slower for some settings. So if you need more speed, I don't think it is a good idea to use that. 

It is quite stable, although I refactored that before pushing, and it is not really tested after the refactoring. I got a report that it crashes :(. From my personal test, it will crash when you set your quantization to 32-bit. @DianaDespa is the quantization working now for you?

**Comment by DianaDespa** [comment] 2017-08-04 13:36
@afaji It crashes even with 2 bit for me after a few iterations (<100). It was either the sorting or some illegal memory access. I will do a PR as well once I'm done with my experiments and code cleanup. But I believe @dr-alan-turing increased the array sizes and said it doesn't crash anymore. Is that correct @dr-alan-turing ?

**Comment by afaji** [comment] 2017-08-04 13:53
I'm not sure what causes the crash, probably there is small committed difference or modifications that I did not realize. anw, you don't have to do any PR to my repo, I did not expect to publish that experimental code in the first place. I suppose you want to make a PR to the marian-dev instead.

**Comment by dr-alan-turing** [comment] 2017-08-04 14:06
I had crashes on the radix sort and indeed solved it by increasing the sizes of the sparse buffers. I will figure out which exact one was the cause in the near future. For now I've just doubled the sizes since they are small enough anyway.

**Comment by afaji** [comment] 2017-08-04 14:11
what is your drop-rate parameter? I suppose it is 0.9?

**Comment by DianaDespa** [comment] 2017-08-04 14:12
I used 0.99 always.

**Comment by DianaDespa** [comment] 2017-08-04 16:00
@afaji Sorry, the invalid access errors could have been due to the fact that I was training on GPUs that were also running other scripts, and at the beginning of the training the memory footprint wasn't that big, but maybe it grew later and made marian fail.

**Comment by dr-alan-turing** [comment] 2017-08-05 03:54
@afaji I'm also on 0.99. The crashes I had were because the sparse buffers were not big enough. This is on multi-node though, and my tests on single node Async worked fine (at some point I thought something was wrong but it turned out I wasn't using the right settings).

**Comment by dr-alan-turing** [comment] 2017-08-16 17:26
I want to add that the approach suggested by @kpu would not decrease memory consumption because instead of 1.5 * |clients| we would have |shards| * |clients|, because each shard stores a copy for each client. This isn't much of an issue since the sharding results in constant memory anyway. It would indeed decrease code complexity and actually improve accuracy because we wouldn't ever lose any clients' history.

**Comment by emjotde** [comment] 2017-10-28 07:43
Closing this for now due to inactivity. Feel free to reopen.

**Closed by emjotde** 2017-10-28 07:43 UTC
