### ISSUE TITLE
Deterministic vocab from spm_train

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian-dev#657] opened 2020-05-26 04:34 UTC
Is there a way to control such that `spm_train` binary that comes with `USE_SENTENCEPIECE` ensures that the sentencepiece model trained with the same data and settings to output the same model?

Or is the `spm_train` already guaranteeing deterministic model by default?

Example, running this command on the same `train.all` seems to output different binary models every time =(

```
~/marian-dev/build/spm_train \
    --bos_id=-1 --eos_id=0 --unk_id=1 \
    --input=train.all \
    --model_prefix=vocab.srctrg.spm \
    --vocab_size=10000
```

**Comment by emjotde** [comment] 2020-05-26 04:56
This is 3rd party software, so we won't touch this. 

Doesn't seem like there is a way to pass a random seed in there so I would guess the answer is "no". We didn't update for a while to the current version of SentencePiece, not sure what is going on there in the original repo. 

Checking the source code for our commit I see multiple calls to functions from `<random>`, but none use a seed. Bad news.

**Comment by alvations** [comment] 2020-05-26 05:00
Yeah, seems like the default behavior is run it and hope for the best. Or do it once and copy it if the model needs to be replicated =(

**Comment by emjotde** [comment] 2020-05-26 05:01
Checked the current version of SentencePiece in the original repo, now way to provide a seed either. Looks like you should direct your feature request there.

**Comment by emjotde** [comment] 2020-05-26 05:01
Closing this.

**Comment by frankseide** [comment] 2020-05-26 16:18
Hi, non-determinism could be caused by parallelization. Is there a way to turn off multi-threading in training?

**Comment by emjotde** [comment] 2020-05-27 03:13
I wasn't able to see what kind of random seed is being used from a quick look. Also @alvations doesn't actually say it's non-deterministic. Would be good to confirm that first.

**Comment by alvations** [comment] 2020-05-27 04:04
Confirming it now =)

Running a couple of times, every `vocab.srctrg.spm.model` binary reports a `diff`

```
~/marian-dev/build/spm_train \
    --bos_id=-1 --eos_id=0 --unk_id=1 \
    --input=train.all \
    --model_prefix=vocab.srctrg.spm \
    --vocab_size=10000
```

**Comment by alvations** [comment] 2020-05-27 04:07
`thread_local static std::mt19937 mt();` in sentencepiece might be the culprit.

**Comment by emjotde** [comment] 2020-05-27 04:09
Hm. If the text version of the vocab is identical, do we have non-determinism?

**Comment by alvations** [comment] 2020-05-27 04:10
That I'm not really sure. But just odd when hash checking across the .model files, so wanted to make sure with the original question in this issue.

**Comment by emjotde** [comment] 2020-05-27 04:11
But if text and all associated output and application is identical, I am not sure we have a problem.

**Comment by alvations** [comment] 2020-05-27 04:13
I think there's no problem, same input output from different .model files when .vocab are the same.

But for my own sanity/security, we've manually hacked the `mt19937` in sentence piece to a fixed random seed on my local version of the code.

**Comment by emjotde** [comment] 2020-05-27 04:13
So for which one are you reporting no differences?

**Comment by alvations** [comment] 2020-05-27 04:15
No difference in .vocab files
No difference in decoder output with different .model files (didn't check carefully, just same BLEU =) )
Yes, found difference in .model files.

So not a real problem I think, only a problem when checking for the hash of the .model file from different runs and a little surprised that it's different.

**Comment by emjotde** [comment] 2020-05-27 04:17
Does diff even handle binary files?
@frankseide OK to close? This should be passed on to the 3rd-party software owner.

**Comment by alvations** [comment] 2020-05-27 04:19
Yes diff does handle binaries, I think. No diff on:

```
cp run1/vocab.srctrg.spm.model x
cp run1/vocab.srctrg.spm.model y
diff x y
```

**Closed** 2020-05-31 04:01 UTC
Labels: enhancement, won't fix
