### ISSUE TITLE
scorer fails when run on CPU

### ISSUE THREAD

**Issue by ugermann** [marian-nmt/marian-dev#539] opened 2019-11-01 16:34 UTC
```
marian-scorer -c scorer.yml -t data.de data.en -d 1
```
works, but with `--cpu-threads 10`, the following happens:

```
marian-scorer -c scorer.yml -t data.de data.en --cpu-threads 10
...
[2019-11-01 16:31:04] Error: Required option 'gemm-type' has not been set
```

```
marian-scorer -c scorer.yml -t data.de data.en --cpu-threads 10 --gemm-type auto
Error: The following arguments were not expected: auto --gemm-type
...
```

**Comment by ugermann** [comment] 2019-11-01 16:37
Also, this means that there's no regression test for scorer on CPU. It's debatable whether or not one should run the scorer on CPU, but occasionally we have excess CPU capacity, so it's a nice thing to have running in the background while the GPUs are busy training models.

**Comment by frankseide** [comment] 2019-11-01 17:01
There is no reason why this should not work. Decoding works, after all. I think this is just a bug, some additional option needs to be set inside the scorer.

**Comment by ugermann** [comment] 2019-11-01 18:21
It's a side effect of the way options are added with different 'modes'. --gem-type is added in addOptionsTranslation(), which is not triggered by the ConfigParser constructor if  the mode is cli::mode::scoring. Most likely the fix is trivial (move the cli.add(...) into the right place), but since I'm not familiar with the whole gemm thing, the person(s) who introduced the gemm stuff should be the ones figuring out where that 'right place' is.

**Comment by ugermann** [comment] 2019-11-01 18:27
... which means that @ykim362 may want to chime in on this.

**Comment by ykim362** [comment] 2019-11-01 18:33
We have removed this option completely on the MS internal branch. I am not sure about the status of this branch. @emjotde Can we merge the internal branch to here?

**Comment by ugermann** [comment] 2019-11-01 18:41
> There is no reason why this should not work. Decoding works, after all. I think this is just a bug, some additional option needs to be set inside the scorer.

I would strongly argue against just a copy-paste to 'fix' things. Each option should be introduced in exactly one place. We already have the problem with divergence between scorer and translator options (e.g., --normalize (float in translator, bool in scorer), --model vs. --models).

**Comment by frankseide** [comment] 2019-11-01 21:23
I fully agree that problems caused by inconsistent code dup should always be fixed by eliminating the code dup.

**Comment by emjotde** [comment] 2019-11-01 23:26
I am ready to merge back. I surprised though that we do not have scorer regressions tests, @snukky ?

**Comment by emjotde** [comment] 2019-11-01 23:29
Seems we fixed that by accident in our master. Contributing back later today. Some more housekeeping to do.

**Comment by ugermann** [comment] 2019-11-01 23:32
> I am ready to merge back. I am surprised though that we do not have scorer regressions tests, @snukky ?

There are scorer regression tests, but not with --cpu-threads. See https://github.com/marian-nmt/marian-regression-tests/issues/32

**Comment by emjotde** [comment] 2019-11-01 23:45
Should be fixed now.

**Comment by frankseide** [comment] 2019-11-04 17:28
You mean the bug, or the regression test?

**Comment by emjotde** [comment] 2019-11-05 03:02
The bug. The regression tests wait for @snukky to come back from EMNLP. And they have their own issue.

**Comment by snukky** [comment] 2019-11-11 09:42
A regression test for scoring on CPU has been added (marian-nmt/marian-regression-tests#32). A thing that may need to be investigated, already mentioned to @emjotde, is a rather consistent difference between scoring on CPU and GPU of 0.01, which seems to be quite large.

**Comment by emjotde** [comment] 2019-11-26 01:45
Are we keeping this open due to the scoring difference or we opening a different issue?

**Comment by emjotde** [comment] 2020-01-06 21:41
Closing.

**Closed by emjotde** 2020-01-06 21:41 UTC
